### ISSUE TITLE
Specify the file for the npm load

### ISSUE THREAD

**Issue by elidiazgt** [NewSpring/meteor-load#3]
In what file i neet to place this code?

var MeteorLoad = require("meteor-load");

var onUseFiles = MeteorLoad.getAllFiles("~/myMeteorProject/packages/myPackage");
var onTestFiles = MeteorLoad.getAllFiles("~/myMeteorProject/packages/myPackage/tests");

serverside?
inside the package files?

its not clear.

**Comment by benwiley** [comment]
You are correct - the documentation is not clear and actually is incorrect!

We use this package as part of a larger node-based build tool called Norma (https://github.com/NewSpring/Norma), specifically norma-meteor-load (https://github.com/NewSpring/norma-meteor-load).  We would love for you to use Norma as it will address the problem of completing the package.js file for you.

Otherwise, you can use this package outside the scope of meteor, in a simple node script, to generate a list of files that you can copy/paste into your package.js like so:

```
var MeteorLoad = require("meteor-load");
var onUseFiles = MeteorLoad.getAllFiles("./path/to/files");
console.log(onUseFiles);
```

Then run `node load.js`

I will update the readme on this project to show this information.  Thanks!

**Comment by benwiley** [comment]
https://github.com/NewSpring/meteor-load/commit/472abb81fe55b1618e8dfff6870c0d78ed66cf78
